In [9]:
import numpy as np
from utils import per_layer_multiply, comparator
from fractions import Fraction

In [10]:
A = np.array([
    [0.1, 0.3, 0.25],
    [0.3, 0.25, 0.2],
    [0.4, 0.2, 0.3]
])

T = np.array([
    [1, 0, 0],
    [0, 1.5, 0],
    [0, 0, 1.25]
])

A = np.linalg.inv(T) @ A @ T

print(A)

[[0.1        0.45       0.3125    ]
 [0.2        0.25       0.16666667]
 [0.32       0.24       0.3       ]]


In [11]:
new_A = np.array([A] * 4)
new_A[2, 2] *= 0.8 
print(new_A)

[[[0.1        0.45       0.3125    ]
  [0.2        0.25       0.16666667]
  [0.32       0.24       0.3       ]]

 [[0.1        0.45       0.3125    ]
  [0.2        0.25       0.16666667]
  [0.32       0.24       0.3       ]]

 [[0.1        0.45       0.3125    ]
  [0.2        0.25       0.16666667]
  [0.256      0.192      0.24      ]]

 [[0.1        0.45       0.3125    ]
  [0.2        0.25       0.16666667]
  [0.32       0.24       0.3       ]]]


In [12]:
new_A[3,:,0] *= 0.85
print(new_A)

[[[0.1        0.45       0.3125    ]
  [0.2        0.25       0.16666667]
  [0.32       0.24       0.3       ]]

 [[0.1        0.45       0.3125    ]
  [0.2        0.25       0.16666667]
  [0.32       0.24       0.3       ]]

 [[0.1        0.45       0.3125    ]
  [0.2        0.25       0.16666667]
  [0.256      0.192      0.24      ]]

 [[0.085      0.45       0.3125    ]
  [0.17       0.25       0.16666667]
  [0.272      0.24       0.3       ]]]


In [13]:
X = np.array([
    [1, 1, 1],
    [1.1, 1.1, 1],
    [1, 1, 1],
    [1.15, 1, 1]
])

In [14]:
Y = X - per_layer_multiply(new_A, X)
Y = Y.T
print(Y)

[[0.1375     0.1825     0.1375     0.28975   ]
 [0.38333333 0.43833333 0.38333333 0.38783333]
 [0.14       0.084      0.312      0.1472    ]]


In [15]:
SY = np.array([1, 1, 1]) @ Y
CSY = SY / SY[0]
print(SY)
print(CSY)

[0.66083333 0.70483333 0.83283333 0.82478333]
[1.         1.0665826  1.26027743 1.24809584]


In [16]:
X[1] - new_A[1]@X[1]

array([0.1825    , 0.43833333, 0.084     ])